### ISSUE TITLE
190325[4wd1]报到处，协作工具和权限分配

### ISSUE THREAD

**Issue by chulung** [totalmind/IA-AI#1]
1.加入zotero群组：[zotero|Groups>IA-AI](https://www.zotero.org/groups/2307357/ia-ai)

2.在本问题下回复以下内容，分配git和zotero权限

- 个人简介：昵称，一句话介绍。
- 角色：组员/观察员/教练
- 技能：（组员填写，如编程、写作、数据检索、ppt、演讲、项目管理、会议组织等，便于分工）
- 空闲时间：（组员填写，用于确认面对面讨论时间，如工作日晚上+周末）

3.使用[git Desktop](https://desktop.github.com/)等工具clone本项目

4.去[项目想法收集](https://github.com/totalmind/IA-AI/issues/2)提交想法和其他问题

**Comment by ichukai** [comment]
回复以下内容

**Comment by ichukai** [comment]
> 1.加入zotero群组：[zotero|Groups>IA-AI](https://www.zotero.org/groups/2307357/ia-ai)
> 
> 2.在本问题下回复以下内容
> 
> * 个人简介：昵称，一句话介绍。
> * 角色：组员/观察员/教练
> * 技能：（组员填写，如写作、数据检索、ppt、演讲、项目管理、会议组织等，便于分工）
> * 空闲时间：（组员填写，用于确认面对面讨论时间，如工作日晚上+周末）
> 
> 3.使用[git Desktop](https://desktop.github.com/)等工具clone本项目
> 
> 4.去[项目想法收集](https://github.com/totalmind/IA-AI/issues/2)提交想法

**Comment by chukai-chaos** [comment]
个人简介：初开，[chukai.link](http://chukai.link)
角色：组长
技能：编程、写作、数据检索
空闲时间：周一、二、四、五、日晚上，周末白天

**Comment by gwrodean** [comment]
个人简介：rodean
角色：组员
技能：写作，演讲，项目管理，会议组织
空闲时间：工作日晚上10点后，周末

**Comment by BaileyHB** [comment]
个人简介：rosy
角色：组员
技能：数据分析，会议记录
空闲时间：工作日早上7点-9点；工作日晚上9点30点后；周末

**Comment by z-flea** [comment]
个人简介：左左
角色：观察员
技能：给建议~
空闲时间：工作日早上7点-9点；工作日晚上9点30点后；周末

**Comment by izhouping** [comment]
个人简介：周平
角色：观察员
技能：督促项目，提供建议
空闲时间：工作日晚上9点30点后；周末视情况而定。

**Comment by wangmhao** [comment]
个人简介：王梦浩
角色：组员
技能：数据检索、演讲、写作、PPT、会议组织、项目管理
空闲时间：工作日晚上+周末

**Comment by DcyWalker** [comment]
个人简介：walker
角色：观察员
技能：给建议、PPT
空闲时间：时间比较自由，不固定
