### ISSUE TITLE
190325[4wd1]项目想法收集

### ISSUE THREAD

**Issue by chulung** [totalmind/IA-AI#2]
大家先把自己的想法写作来，后续安排时间面对面讨论。
一些参考问题~
假如没有任何知识和技能上的困难：
1.  我想解决我对人工智能领域的哪些问题？
2. 我想知道人工智能领域的哪些知识？
3. 如果这次项目只解决一个问题，你想解决什么？
4. 这次项目我想得到的最好成果是什么
5. 还有什么其他问题想提给大家的？

**Comment by chukai-chaos** [comment]
我想解决我对人工智能领域的哪些问题？
我想知道人工智能领域的哪些知识？
1. 人工智能的发展路径是什么，关键转折点有哪些
2. 人工智能的主要研究领域有哪些，当下大牛、实验室地域分布
3. 现在是人工智能的大好时期吗，还是只是多数人的狂欢
4. 如果想加入人工智能领域，普通的开发者应该如何切入，如何优雅的转行人工智能
5. 国内的人工智能进展如何，未来的规划如何（各公司的规划，国家的规划）
6. 人工智能现在的学习路径

如果这次项目只解决一个问题，我想解决什么？
人工智能的最小全局知识是什么

这次项目我想得到的最好成果是什么
一份涵盖学术和商业的最小全局知识报告

**Comment by gwrodean** [comment]
1、人工智能现在的发展情况，实验室技术和应用落地之间的gap值有多少
2、国内&国外人工智能的实际应用情况，是否存在国内外差距？如果有，有多大
3、目前头部的人工智能应用公司都有哪些，分别是什么方向（无人机、无人车、智能助理？……）
4、人工智能5-10年的发展预期是怎样？技术节点会有哪些?
5、人工智能的运营方向有哪些？即人的“运营”在人工智能的发展中，需要起到什么作用
6、目前对人工智能的介绍，哪些地方最专业，如何获取这些专业信息

**Comment by wangmhao** [comment]
1. 我想解决人工智能领域的哪些问题？
将抽象的人工智能具象化，便于传播
2. 我想知道人工智能领域的哪些知识？
了解人工智能技术的最小全局知识
3. 这次项目我想得到的最好成果是什么？
- 一份人工智能在商业领域深入应用的报告
- 一个套利机会
4. 还有什么问题想提的
伙伴们加油啊，进度撸起来

**Comment by ichukai** [comment]
> 我想解决我对人工智能领域的哪些问题？
> 我想知道人工智能领域的哪些知识？
> 
> 1. 人工智能的发展路径是什么，关键转折点有哪些
> 2. 人工智能的主要研究领域有哪些，当下大牛、实验室地域分布
> 3. 现在是人工智能的大好时期吗，还是只是多数人的狂欢
> 4. 如果想加入人工智能领域，普通的开发者应该如何切入，如何优雅的转行人工智能
> 5. 国内的人工智能进展如何，未来的规划如何（各公司的规划，国家的规划）
> 6. 人工智能现在的学习路径
> 
> 如果这次项目只解决一个问题，我想解决什么？
> 人工智能的最小全局知识是什么
> 
> 这次项目我想得到的最好成果是什么
> 一份涵盖学术和商业的最小全局知识报告

**Comment by BaileyHB** [comment]
我想解决我对人工智能领域的哪些问题？
我想知道人工智能领域的哪些知识？

1.人工智能学科的关键知识点，学科的发展历程，研究的实验室以及重要的研究人员
2.头部公司人工智能的应用领域，以及相关城市的产业分析，理论和实践的差距
3.人工智能行业未来5-10年的发展趋势
4.如果想从事人工智能最少需要掌握哪些技能，有哪些学习路径和资料
5.中国的人工智能和国外人工智能在学术和商业领域发展的对比

这个项目我想到的最好的成果：
人工智能在学术和商业领域的最小全局认识
